"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { getSupabaseClient } from "@/lib/supabase-client";
import { distanceNm } from "@/lib/voyage-engine";
import type { StoredVoyagePlan } from "@/lib/use-voyage-plan";
import { parseRouteFile } from "@/lib/route-import";

interface Props { organizationId:string; vesselId:string; vesselName:string; currentPosition:{lat:number;lon:number}; plan:StoredVoyagePlan|null; loading:boolean; onSaved:()=>Promise<void>; }
type DraftWaypoint={name:string;lat:string;lon:string};

export default function VoyageWorkspace({organizationId,vesselId,vesselName,currentPosition,plan,loading,onSaved}:Props){
 const supabase=getSupabaseClient(); const fileInput=useRef<HTMLInputElement>(null);
 const [departure,setDeparture]=useState(""); const [destination,setDestination]=useState(""); const [departureLat,setDepartureLat]=useState(""); const [departureLon,setDepartureLon]=useState(""); const [destinationLat,setDestinationLat]=useState(""); const [destinationLon,setDestinationLon]=useState(""); const [speed,setSpeed]=useState("8.0"); const [plannedDeparture,setPlannedDeparture]=useState(""); const [waypoints,setWaypoints]=useState<DraftWaypoint[]>([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null); const [importInfo,setImportInfo]=useState<string|null>(null);
 useEffect(()=>{if(!plan)return;setDeparture(plan.departure);setDestination(plan.destination);setDepartureLat(formatMarinerCoord(plan.departurePosition.lat,true));setDepartureLon(formatMarinerCoord(plan.departurePosition.lon,false));setDestinationLat(formatMarinerCoord(plan.destinationPosition.lat,true));setDestinationLon(formatMarinerCoord(plan.destinationPosition.lon,false));setSpeed(String(plan.plannedSpeedKt));setPlannedDeparture(plan.plannedDepartureAt?toLocalInput(plan.plannedDepartureAt):"");setWaypoints(plan.waypoints.map(wp=>({name:wp.name,lat:formatMarinerCoord(wp.position.lat,true),lon:formatMarinerCoord(wp.position.lon,false)})));},[plan?.id]);
 const routeDistance=useMemo(()=>{const dep=point(departureLat,departureLon),dest=point(destinationLat,destinationLon);if(!dep||!dest)return null;const pts=[dep,...waypoints.map(w=>point(w.lat,w.lon)).filter(Boolean) as {lat:number;lon:number}[],dest];return pts.slice(0,-1).reduce((s,p,i)=>s+distanceNm(p,pts[i+1]),0);},[departureLat,departureLon,destinationLat,destinationLon,waypoints]);
 function addWaypoint(){setWaypoints(w=>[...w,{name:`WP${String(w.length+1).padStart(2,"0")}`,lat:"",lon:""}]);} function updateWaypoint(i:number,k:keyof DraftWaypoint,v:string){setWaypoints(w=>w.map((x,n)=>n===i?{...x,[k]:v}:x));} function moveWaypoint(i:number,d:number){setWaypoints(w=>{const n=[...w],t=i+d;if(t<0||t>=n.length)return n;[n[i],n[t]]=[n[t],n[i]];return n;});} function removeWaypoint(i:number){setWaypoints(w=>w.filter((_,n)=>n!==i));} function useCurrentDeparture(){setDepartureLat(formatMarinerCoord(currentPosition.lat,true));setDepartureLon(formatMarinerCoord(currentPosition.lon,false));if(!departure)setDeparture("Current position");}
 async function importRoute(file:File){setMessage(null);try{const imported=parseRouteFile(await file.text(),file.name);const pts=imported.waypoints;const first=pts[0],last=pts[pts.length-1],middle=pts.slice(1,-1);setDeparture(first.name);setDepartureLat(formatMarinerCoord(first.lat,true));setDepartureLon(formatMarinerCoord(first.lon,false));setDestination(last.name);setDestinationLat(formatMarinerCoord(last.lat,true));setDestinationLon(formatMarinerCoord(last.lon,false));setWaypoints(middle.map(p=>({name:p.name,lat:formatMarinerCoord(p.lat,true),lon:formatMarinerCoord(p.lon,false)})));setImportInfo(`${imported.format} · ${pts.length} ROUTE POINTS · ${imported.name||file.name}`);setMessage("Route imported. Verify the route points and distance before saving or activating.");}catch(e:any){setImportInfo(null);setMessage(e?.message||"Unable to import route.");}finally{if(fileInput.current)fileInput.current.value="";}}
 async function save(activate:boolean){const dep=point(departureLat,departureLon),dest=point(destinationLat,destinationLon),plannedSpeed=Number(speed);if(!departure.trim()||!destination.trim()||!dep||!dest||!Number.isFinite(plannedSpeed)||plannedSpeed<=0){setMessage("Enter departure, destination, valid positions, and planned speed.");return;}const parsed=waypoints.map(w=>({...w,position:point(w.lat,w.lon)}));if(parsed.some(w=>!w.name.trim()||!w.position)){setMessage("Complete every waypoint name and position, or remove the unfinished waypoint.");return;}setSaving(true);setMessage(null);try{let voyageId=plan?.id;const payload={organization_id:organizationId,vessel_id:vesselId,vessel_name:vesselName,departure_name:departure.trim(),destination_name:destination.trim(),departure_lat:dep.lat,departure_lon:dep.lon,destination_lat:dest.lat,destination_lon:dest.lon,planned_speed_kt:plannedSpeed,planned_departure_at:plannedDeparture?new Date(plannedDeparture).toISOString():null,status:activate?"active":"planned",started_at:activate?new Date().toISOString():null,updated_at:new Date().toISOString()};if(voyageId){const{error}=await supabase.from("voyages").update(payload).eq("id",voyageId);if(error)throw error;const{error:de}=await supabase.from("voyage_waypoints").delete().eq("voyage_id",voyageId);if(de)throw de;}else{const{data,error}=await supabase.from("voyages").insert(payload).select("id").single();if(error)throw error;voyageId=data.id;}if(parsed.length){const{error}=await supabase.from("voyage_waypoints").insert(parsed.map((w,i)=>({voyage_id:voyageId,sequence_no:i+1,name:w.name.trim(),lat:w.position!.lat,lon:w.position!.lon})));if(error)throw error;}await onSaved();setMessage(activate?"Voyage activated. Operations is now using this route.":"Voyage saved as planned.");}catch(e:any){setMessage(e?.message||"Unable to save voyage.");}finally{setSaving(false);}}
 if(loading)return <section className="panel workspaceShell"><div className="eyebrow">VOYAGE</div><h2>Loading voyage...</h2></section>;
 return <section className="voyageWorkspace"><article className="panel voyageBuilder"><div className="workspaceHeading"><div><div className="eyebrow">ROUTE IMPORT & VALIDATION</div><h2>{plan?`${plan.status.toUpperCase()} VOYAGE`:"Create voyage"}</h2></div><div className="cloudBadge">{plan?"CLOUD SAVED":"NEW PLAN"}</div></div>
 <div className="routeImportBox"><div><div className="sectionTitle">IMPORT ECDIS / PLANNING ROUTE</div><p>RTZ and GPX supported. SEAVANT will load the route for verification before anything is activated.</p>{importInfo&&<strong>{importInfo}</strong>}</div><input ref={fileInput} hidden type="file" accept=".rtz,.gpx,application/xml,text/xml" onChange={e=>{const f=e.target.files?.[0];if(f)void importRoute(f);}}/><button className="primaryAction compactAction" type="button" onClick={()=>fileInput.current?.click()}>IMPORT ROUTE</button></div>
 <div className="voyageFormGrid"><label>DEPARTURE<input value={departure} onChange={e=>setDeparture(e.target.value)}/></label><label>DESTINATION<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label>DEPARTURE LAT · DD° MM.MMM′ N/S<input value={departureLat} onChange={e=>setDepartureLat(e.target.value)} inputMode="text"/></label><label>DEPARTURE LON · DDD° MM.MMM′ E/W<input value={departureLon} onChange={e=>setDepartureLon(e.target.value)} inputMode="text"/></label><label>DESTINATION LAT · DD° MM.MMM′ N/S<input value={destinationLat} onChange={e=>setDestinationLat(e.target.value)} inputMode="text"/></label><label>DESTINATION LON · DDD° MM.MMM′ E/W<input value={destinationLon} onChange={e=>setDestinationLon(e.target.value)} inputMode="text"/></label><label>PLANNED SPEED · KT<input value={speed} onChange={e=>setSpeed(e.target.value)} inputMode="decimal"/></label><label>PLANNED DEPARTURE<input type="datetime-local" value={plannedDeparture} onChange={e=>setPlannedDeparture(e.target.value)}/></label></div><button className="secondaryAction voyageUtility" type="button" onClick={useCurrentDeparture}>USE CURRENT POSITION AS DEPARTURE</button>
 <div className="waypointHeader"><div><div className="sectionTitle">ROUTE POINTS</div><p>Imported intermediate points shown in degrees and decimal minutes. Manual editing is available for corrections.</p></div><button className="secondaryAction voyageUtility" type="button" onClick={addWaypoint}>+ ADD POINT</button></div><div className="waypointTable">{waypoints.length?waypoints.map((w,i)=><div className="waypointRow" key={i}><span className="waypointSeq">{String(i+1).padStart(2,"0")}</span><input value={w.name} onChange={e=>updateWaypoint(i,"name",e.target.value)}/><input value={w.lat} inputMode="text" aria-label={`${w.name} latitude`} onChange={e=>updateWaypoint(i,"lat",e.target.value)}/><input value={w.lon} inputMode="text" aria-label={`${w.name} longitude`} onChange={e=>updateWaypoint(i,"lon",e.target.value)}/><div className="waypointActions"><button onClick={()=>moveWaypoint(i,-1)} disabled={i===0}>↑</button><button onClick={()=>moveWaypoint(i,1)} disabled={i===waypoints.length-1}>↓</button><button onClick={()=>removeWaypoint(i)}>×</button></div></div>):<div className="emptyState">Import an RTZ/GPX route, or use a direct route.</div>}</div>
 <div className="voyageBuilderFooter"><div>{routeDistance!==null&&<><span>ROUTE DISTANCE</span><strong>{routeDistance.toFixed(1)} NM</strong></>}</div><div className="voyageSaveActions"><button className="secondaryAction" disabled={saving} onClick={()=>void save(false)}>SAVE PLAN</button><button className="primaryAction compactAction" disabled={saving} onClick={()=>void save(true)}>ACTIVATE VOYAGE</button></div></div>{message&&<div className="authMessage">{message}</div>}</article></section>;
}

function formatMarinerCoord(value:number,isLat:boolean){
 const hemi=isLat?(value>=0?"N":"S"):(value>=0?"E":"W"); const abs=Math.abs(value); let deg=Math.floor(abs); let min=(abs-deg)*60; if(min>=59.9995){deg+=1;min=0;} const degWidth=isLat?2:3; return `${String(deg).padStart(degWidth,"0")}° ${min.toFixed(3).padStart(6,"0")}′ ${hemi}`;
}
function parseCoord(value:string,isLat:boolean){
 const text=value.trim().toUpperCase().replace(/[’']/g,"′");
 const decimal=Number(text); if(Number.isFinite(decimal)){const limit=isLat?90:180;return decimal>=-limit&&decimal<=limit?decimal:null;}
 const hemi=text.match(/[NSEW]/)?.[0]; const nums=text.replace(/[NSEW]/g,"").match(/-?\d+(?:\.\d+)?/g)?.map(Number)??[]; if(nums.length<2)return null;
 let result=Math.abs(nums[0])+nums[1]/60; if(nums[1]>=60)return null; if(hemi==="S"||hemi==="W"||nums[0]<0)result*=-1; if(isLat&&hemi&&!["N","S"].includes(hemi))return null; if(!isLat&&hemi&&!["E","W"].includes(hemi))return null; const limit=isLat?90:180; return result>=-limit&&result<=limit?result:null;
}
function point(lat:string,lon:string){const a=parseCoord(lat,true),b=parseCoord(lon,false);return a!==null&&b!==null?{lat:a,lon:b}:null;} function toLocalInput(iso:string){const d=new Date(iso),local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
